site_name: 全国大学生电子设计竞赛
site_url: https://nuedc.org/
repo_url: https://github.com/chenshuo/nuedc
edit_uri: ''
site_author: 陈硕

theme:
  name: mkdocs
  analytics:
    gtag: G-KF122GXJGS
extra_css: [extra.css]
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_HTML
markdown_extensions:
  - mdx_math
plugins:
  - mkdocs-jupyter:
      no_input: True
      remove_tag_config:
        remove_input_tags:
          - hide_code
        remove_cell_tags:
          - hide_cell


nav:
 - 首页: 'index.md'
 - 历届试题: problems.md
 - 器件手册: datasheets.md
 - 资料笔记:
   - 资料: notes.md
   - 稳压与基准: regulator.md
   - 741 运放: 741.md
   - RC4558 运放: rc4558.ipynb
   - 定性使用 BJT 三极管: bjt-circuits.ipynb
 - 关于: 'about.md'
