site_name: 全国大学生电子设计竞赛
site_url: https://nuedc.org/
repo_url: https://github.com/chenshuo/nuedc
edit_uri: ''
site_author: 陈硕

theme:
  name: mkdocs
  analytics:
    gtag: G-KF122GXJGS

nav:
 - 首页: 'index.md'
 - 历届试题: problems.md
 - 器件手册: datasheets.md
 - 笔记: notes.md
 - 关于: 'about.md'
